export interface TarotCard {
  id: number;
  name: string;
  image: string;
  searchKey: string; // AI analizi için İngilizce anahtar kelime
}

export const TAROT_DECK: TarotCard[] = [
  // --- MAJOR ARCANA (BÜYÜK ARKANA - 22 KART) ---
  { id: 0, name: "Joker (The Fool)", searchKey: "The Fool", image: "https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg" },
  { id: 1, name: "Büyücü (The Magician)", searchKey: "The Magician", image: "https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg" },
  { id: 2, name: "Azize (The High Priestess)", searchKey: "The High Priestess", image: "https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg" },
  { id: 3, name: "İmparatoriçe (The Empress)", searchKey: "The Empress", image: "https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg" },
  { id: 4, name: "İmparator (The Emperor)", searchKey: "The Emperor", image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg" },
  { id: 5, name: "Aziz (The Hierophant)", searchKey: "The Hierophant", image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg" },
  { id: 6, name: "Aşıklar (The Lovers)", searchKey: "The Lovers", image: "https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg" },
  { id: 7, name: "Savaş Arabası (The Chariot)", searchKey: "The Chariot", image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg" },
  { id: 8, name: "Güç (Strength)", searchKey: "Strength", image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg" },
  { id: 9, name: "Ermiş (The Hermit)", searchKey: "The Hermit", image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg" },
  { id: 10, name: "Kader Çarkı (Wheel of Fortune)", searchKey: "Wheel of Fortune", image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg" },
  { id: 11, name: "Adalet (Justice)", searchKey: "Justice", image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg" },
  { id: 12, name: "Asılan Adam (The Hanged Man)", searchKey: "The Hanged Man", image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg" },
  { id: 13, name: "Ölüm (Death)", searchKey: "Death", image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg" },
  { id: 14, name: "Denge (Temperance)", searchKey: "Temperance", image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg" },
  { id: 15, name: "Şeytan (The Devil)", searchKey: "The Devil", image: "https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg" },
  { id: 16, name: "Yıkılan Kule (The Tower)", searchKey: "The Tower", image: "https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg" },
  { id: 17, name: "Yıldız (The Star)", searchKey: "The Star", image: "https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg" },
  { id: 18, name: "Ay (The Moon)", searchKey: "The Moon", image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg" },
  { id: 19, name: "Güneş (The Sun)", searchKey: "The Sun", image: "https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg" },
  { id: 20, name: "Mahkeme (Judgement)", searchKey: "Judgement", image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg" },
  { id: 21, name: "Dünya (The World)", searchKey: "The World", image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg" },

  // --- WANDS (DEĞNEKLER - ATEŞ GRUBU) ---
  { id: 22, name: "Değnek Ası", searchKey: "Ace of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg" },
  { id: 23, name: "Değnek İkilisi", searchKey: "Two of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg" },
  { id: 24, name: "Değnek Üçlüsü", searchKey: "Three of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg" },
  { id: 25, name: "Değnek Dörtlüsü", searchKey: "Four of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg" },
  { id: 26, name: "Değnek Beşlisi", searchKey: "Five of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg" },
  { id: 27, name: "Değnek Altılısı", searchKey: "Six of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg" },
  { id: 28, name: "Değnek Yedilisi", searchKey: "Seven of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg" },
  { id: 29, name: "Değnek Sekizlisi", searchKey: "Eight of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg" },
  { id: 30, name: "Değnek Dokuzlusu", searchKey: "Nine of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Tarot_Nine_of_Wands.jpg" },
  { id: 31, name: "Değnek Onlusu", searchKey: "Ten of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg" },
  { id: 32, name: "Değnek Prensi", searchKey: "Page of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/6/6a/WandsPage.jpg" },
  { id: 33, name: "Değnek Şövalyesi", searchKey: "Knight of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/1/16/WandsKnight.jpg" },
  { id: 34, name: "Değnek Kraliçesi", searchKey: "Queen of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/WandsQueen.jpg" },
  { id: 35, name: "Değnek Kralı", searchKey: "King of Wands", image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/WandsKing.jpg" },

  // --- CUPS (KUPALAR - SU GRUBU) ---
  { id: 36, name: "Kupa Ası", searchKey: "Ace of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Cups01.jpg" },
  { id: 37, name: "Kupa İkilisi", searchKey: "Two of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg" },
  { id: 38, name: "Kupa Üçlüsü", searchKey: "Three of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg" },
  { id: 39, name: "Kupa Dörtlüsü", searchKey: "Four of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg" },
  { id: 40, name: "Kupa Beşlisi", searchKey: "Five of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg" },
  { id: 41, name: "Kupa Altılısı", searchKey: "Six of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg" },
  { id: 42, name: "Kupa Yedilisi", searchKey: "Seven of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg" },
  { id: 43, name: "Kupa Sekizlisi", searchKey: "Eight of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg" },
  { id: 44, name: "Kupa Dokuzlusu", searchKey: "Nine of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg" },
  { id: 45, name: "Kupa Onlusu", searchKey: "Ten of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg" },
  { id: 46, name: "Kupa Prensi", searchKey: "Page of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/CupsPage.jpg" },
  { id: 47, name: "Kupa Şövalyesi", searchKey: "Knight of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/CupsKnight.jpg" },
  { id: 48, name: "Kupa Kraliçesi", searchKey: "Queen of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/6/61/CupsQueen.jpg" },
  { id: 49, name: "Kupa Kralı", searchKey: "King of Cups", image: "https://upload.wikimedia.org/wikipedia/commons/0/04/CupsKing.jpg" },

  // --- SWORDS (KILIÇLAR - HAVA GRUBU) ---
  { id: 50, name: "Kılıç Ası", searchKey: "Ace of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg" },
  { id: 51, name: "Kılıç İkilisi", searchKey: "Two of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/9/92/Swords02.jpg" },
  { id: 52, name: "Kılıç Üçlüsü", searchKey: "Three of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg" },
  { id: 53, name: "Kılıç Dörtlüsü", searchKey: "Four of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg" },
  { id: 54, name: "Kılıç Beşlisi", searchKey: "Five of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg" },
  { id: 55, name: "Kılıç Altılısı", searchKey: "Six of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg" },
  { id: 56, name: "Kılıç Yedilisi", searchKey: "Seven of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg" },
  { id: 57, name: "Kılıç Sekizlisi", searchKey: "Eight of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg" },
  { id: 58, name: "Kılıç Dokuzlusu", searchKey: "Nine of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg" },
  { id: 59, name: "Kılıç Onlusu", searchKey: "Ten of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg" },
  { id: 60, name: "Kılıç Prensi", searchKey: "Page of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/SwordsPage.jpg" },
  { id: 61, name: "Kılıç Şövalyesi", searchKey: "Knight of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/b/b0/SwordsKnight.jpg" },
  { id: 62, name: "Kılıç Kraliçesi", searchKey: "Queen of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/SwordsQueen.jpg" },
  { id: 63, name: "Kılıç Kralı", searchKey: "King of Swords", image: "https://upload.wikimedia.org/wikipedia/commons/3/33/SwordsKing.jpg" },

  // --- PENTACLES (TILSIMLAR - TOPRAK GRUBU) ---
  { id: 64, name: "Tılsım Ası", searchKey: "Ace of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg" },
  { id: 65, name: "Tılsım İkilisi", searchKey: "Two of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg" },
  { id: 66, name: "Tılsım Üçlüsü", searchKey: "Three of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg" },
  { id: 67, name: "Tılsım Dörtlüsü", searchKey: "Four of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg" },
  { id: 68, name: "Tılsım Beşlisi", searchKey: "Five of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg" },
  { id: 69, name: "Tılsım Altılısı", searchKey: "Six of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg" },
  { id: 70, name: "Tılsım Yedilisi", searchKey: "Seven of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Pents07.jpg" },
  { id: 71, name: "Tılsım Sekizlisi", searchKey: "Eight of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg" },
  { id: 72, name: "Tılsım Dokuzlusu", searchKey: "Nine of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg" },
  { id: 73, name: "Tılsım Onlusu", searchKey: "Ten of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg" },
  { id: 74, name: "Tılsım Prensi", searchKey: "Page of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/PentsPage.jpg" },
  { id: 75, name: "Tılsım Şövalyesi", searchKey: "Knight of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/PentsKnight.jpg" },
  { id: 76, name: "Tılsım Kraliçesi", searchKey: "Queen of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/8/88/PentsQueen.jpg" },
  { id: 77, name: "Tılsım Kralı", searchKey: "King of Pentacles", image: "https://upload.wikimedia.org/wikipedia/commons/1/1c/PentsKing.jpg" },
];